# Generated by Django 3.2.9 on 2022-01-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('author', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('r', 'read'), ('t', 'to_be_read')], default='t', max_length=1)),
                ('target', models.DateField()),
            ],
        ),
    ]
