# Generated by Django 3.2.9 on 2022-01-05 16:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('confidence', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GreatJob',
            new_name='GreateJob',
        ),
    ]
