# Generated by Django 3.2.9 on 2021-12-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_transaction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
