# Generated by Django 3.2.9 on 2021-12-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='day',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='todays_amount',
            field=models.IntegerField(default=10000),
        ),
    ]
